"""
Project initialization system for TATty Agent

This module handles the initialization of projects with TATty Agent,
creating external artifact folders and setting up BAML assets outside
the package installation to avoid pollution.
"""
import os
import shutil
from pathlib import Path
from typing import Optional, List, Dict, Any


class ProjectInitializer:
    """Handles project setup and artifact folder management"""

    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root).resolve()
        self.standard_folders = {
            "scripts": "Python scripts, code generators, analysis tools",
            "data": "CSV files, datasets, JSON files, text data",
            "visualization": "Plots, charts, images, visual outputs",
            "documents": "Reports, MD, PDF, Excel, PPT files"
        }

    def initialize_project(self, force: bool = False) -> Dict[str, Any]:
        """
        Initialize a project with TATty Agent artifact folders and templates

        Args:
            force: Overwrite existing files if they exist

        Returns:
            Dictionary with initialization results
        """
        results = {
            "success": True,
            "created_folders": [],
            "created_files": [],
            "existing_files": [],
            "errors": []
        }

        try:
            # Create standard artifact folders
            for folder, description in self.standard_folders.items():
                folder_path = self.project_root / folder
                if not folder_path.exists():
                    folder_path.mkdir(parents=True, exist_ok=True)
                    results["created_folders"].append(str(folder))

                    # Create README in each folder
                    readme_path = folder_path / "README.md"
                    readme_content = f"# {folder.title()} Folder\n\n{description}\n\nGenerated by TATty Agent.\n"
                    readme_path.write_text(readme_content)
                    results["created_files"].append(str(readme_path.relative_to(self.project_root)))

            # Create .env template
            env_path = self.project_root / ".env"
            if not env_path.exists() or force:
                env_content = """# TATty Agent Environment Configuration
# Copy this file and fill in your API keys

# OpenAI API Key (for GPT models)
OPENAI_API_KEY=your_openai_key_here

# Boundary ML API Key (for BAML)
BOUNDARY_API_KEY=your_boundary_key_here

# Optional: Specify working directory
# TATTY_WORKING_DIR=.

# Optional: Model preferences
# TATTY_DEFAULT_MODEL=gpt-4
# TATTY_FAST_MODEL=gpt-3.5-turbo

# Optional: Enable debug mode
# TATTY_DEBUG=false
"""
                env_path.write_text(env_content)
                results["created_files"].append(".env")
            else:
                results["existing_files"].append(".env")

            # Create .gitignore additions
            gitignore_path = self.project_root / ".gitignore"
            gitignore_additions = """
# TATty Agent generated files
.tatty/
*.tatty.log
.mypy_cache/
__pycache__/
*.pyc
*.pyo
.pytest_cache/

# Environment files
.env
.env.local
.env.*.local

# BAML generated files
baml_client/
"""

            if gitignore_path.exists():
                # Append to existing .gitignore if TATty section doesn't exist
                existing_content = gitignore_path.read_text()
                if "# TATty Agent generated files" not in existing_content:
                    gitignore_path.write_text(existing_content + gitignore_additions)
                    results["created_files"].append(".gitignore (updated)")
                else:
                    results["existing_files"].append(".gitignore (TATty section exists)")
            else:
                gitignore_path.write_text(gitignore_additions.strip())
                results["created_files"].append(".gitignore")

            # Copy BAML template assets
            baml_result = self._setup_baml_assets(force)
            results["created_files"].extend(baml_result.get("created_files", []))
            results["existing_files"].extend(baml_result.get("existing_files", []))
            results["errors"].extend(baml_result.get("errors", []))

        except Exception as e:
            results["success"] = False
            results["errors"].append(f"Initialization failed: {str(e)}")

        return results

    def _setup_baml_assets(self, force: bool = False) -> Dict[str, List[str]]:
        """Set up BAML template assets in the project"""
        results = {"created_files": [], "existing_files": [], "errors": []}

        try:
            # Get the package's assets directory
            package_root = Path(__file__).parent.parent
            assets_dir = package_root / "assets"

            if not assets_dir.exists():
                results["errors"].append("BAML assets directory not found in package")
                return results

            # Copy baml_src template if it exists
            template_baml_src = assets_dir / "baml_src"
            project_baml_src = self.project_root / "baml_src"

            if template_baml_src.exists():
                if not project_baml_src.exists() or force:
                    if project_baml_src.exists() and force:
                        shutil.rmtree(project_baml_src)

                    shutil.copytree(template_baml_src, project_baml_src)
                    results["created_files"].append("baml_src/ (from template)")
                else:
                    results["existing_files"].append("baml_src/")

            # Create pyproject.toml additions for BAML if file doesn't exist
            pyproject_path = self.project_root / "pyproject.toml"
            if not pyproject_path.exists():
                pyproject_content = """[project]
name = "tatty-agent-project"
version = "0.1.0"
description = "Project initialized with TATty Agent"
dependencies = [
    "tatty-agent",
    "python-dotenv",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
"""
                pyproject_path.write_text(pyproject_content)
                results["created_files"].append("pyproject.toml")

        except Exception as e:
            results["errors"].append(f"BAML asset setup failed: {str(e)}")

        return results

    def check_project_status(self) -> Dict[str, Any]:
        """Check the current status of the project initialization"""
        status = {
            "initialized": True,
            "folders": {},
            "files": {},
            "missing": [],
            "recommendations": []
        }

        # Check folders
        for folder, description in self.standard_folders.items():
            folder_path = self.project_root / folder
            status["folders"][folder] = {
                "exists": folder_path.exists(),
                "description": description,
                "file_count": len(list(folder_path.glob("*"))) if folder_path.exists() else 0
            }

            if not folder_path.exists():
                status["initialized"] = False
                status["missing"].append(f"folder: {folder}")

        # Check important files
        important_files = {
            ".env": "Environment configuration",
            ".gitignore": "Git ignore rules",
            "baml_src/": "BAML tool definitions"
        }

        for file, description in important_files.items():
            file_path = self.project_root / file
            exists = file_path.exists()
            status["files"][file] = {
                "exists": exists,
                "description": description
            }

            if not exists:
                status["missing"].append(f"file: {file}")

        # Generate recommendations
        if not status["initialized"]:
            status["recommendations"].append("Run 'tatty-init' to initialize the project")

        if not (self.project_root / ".env").exists():
            status["recommendations"].append("Create .env file with your API keys")

        if not (self.project_root / "baml_src").exists():
            status["recommendations"].append("Set up BAML configuration for custom tools")

        return status

    def clean_project(self, confirm: bool = False) -> Dict[str, Any]:
        """
        Clean up TATty Agent generated files and folders

        Args:
            confirm: Must be True to actually perform cleanup

        Returns:
            Dictionary with cleanup results
        """
        if not confirm:
            return {
                "success": False,
                "error": "Cleanup requires explicit confirmation (confirm=True)"
            }

        results = {
            "success": True,
            "removed_folders": [],
            "removed_files": [],
            "errors": []
        }

        try:
            # Remove artifact folders (but only if they're empty or contain only README)
            for folder in self.standard_folders.keys():
                folder_path = self.project_root / folder
                if folder_path.exists():
                    contents = list(folder_path.glob("*"))
                    if not contents or (len(contents) == 1 and contents[0].name == "README.md"):
                        shutil.rmtree(folder_path)
                        results["removed_folders"].append(folder)

            # Remove generated files
            cleanup_files = [".env", "baml_client"]
            for file in cleanup_files:
                file_path = self.project_root / file
                if file_path.exists():
                    if file_path.is_dir():
                        shutil.rmtree(file_path)
                    else:
                        file_path.unlink()
                    results["removed_files"].append(file)

        except Exception as e:
            results["success"] = False
            results["errors"].append(f"Cleanup failed: {str(e)}")

        return results