# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (21)
# #########################################################################

class AgentTool(BaseModel):
    action: typing_extensions.Literal['Agent']
    description: str
    prompt: str

class BashTool(BaseModel):
    action: typing_extensions.Literal['Bash']
    command: str
    timeout: typing.Optional[int] = None
    description: typing.Optional[str] = None

class EditOperation(BaseModel):
    old_string: str
    new_string: str
    replace_all: typing.Optional[bool] = None

class EditTool(BaseModel):
    action: typing_extensions.Literal['Edit']
    file_path: str
    old_string: str
    new_string: str
    replace_all: typing.Optional[bool] = None

class ExitPlanModeTool(BaseModel):
    action: typing_extensions.Literal['exit_plan_mode']
    plan: str

class GlobTool(BaseModel):
    action: typing_extensions.Literal['Glob']
    pattern: str
    path: typing.Optional[str] = None

class GrepTool(BaseModel):
    action: typing_extensions.Literal['Grep']
    pattern: str
    path: typing.Optional[str] = None
    include: typing.Optional[str] = None

class LSTool(BaseModel):
    action: typing_extensions.Literal['LS']
    path: str
    ignore: typing.Optional[typing.List[str]] = None

class Message(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    message: typing.Union[str, "BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "AgentTool"]

class MultiEditTool(BaseModel):
    action: typing_extensions.Literal['MultiEdit']
    file_path: str
    edits: typing.List["EditOperation"]

class NotebookEditTool(BaseModel):
    action: typing_extensions.Literal['NotebookEdit']
    notebook_path: str
    cell_number: int
    new_source: str
    cell_type: typing.Optional[str] = None
    edit_mode: typing.Optional[str] = None

class NotebookReadTool(BaseModel):
    action: typing_extensions.Literal['NotebookRead']
    notebook_path: str

class ReadTool(BaseModel):
    action: typing_extensions.Literal['Read']
    file_path: str
    offset: typing.Optional[int] = None
    limit: typing.Optional[int] = None

class ReplyToUser(BaseModel):
    action: typing_extensions.Literal['reply_to_user']
    message: str

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class TodoItem(BaseModel):
    content: str
    status: typing.Union[typing_extensions.Literal['pending'], typing_extensions.Literal['in_progress'], typing_extensions.Literal['completed']]
    priority: typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]
    id: str

class TodoReadTool(BaseModel):
    action: typing_extensions.Literal['TodoRead']

class TodoWriteTool(BaseModel):
    action: typing_extensions.Literal['TodoWrite']
    todos: typing.List["TodoItem"]

class WebFetchTool(BaseModel):
    action: typing_extensions.Literal['WebFetch']
    url: str
    prompt: str
    save_to_file: typing.Optional[str] = None

class WebSearchTool(BaseModel):
    action: typing_extensions.Literal['WebSearch']
    query: str
    allowed_domains: typing.Optional[typing.List[str]] = None
    blocked_domains: typing.Optional[typing.List[str]] = None

class WriteTool(BaseModel):
    action: typing_extensions.Literal['Write']
    file_path: str
    content: str

# #########################################################################
# Generated type aliases (3)
# #########################################################################


AgentTools: typing_extensions.TypeAlias = typing.Union["BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "AgentTool"]


ScaryTools: typing_extensions.TypeAlias = typing.Union["EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "TodoWriteTool"]


SubAgentTools: typing_extensions.TypeAlias = typing.Union["BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool"]
