# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (40)
# #########################################################################

class AgentTool(BaseModel):
    action: typing_extensions.Literal['Agent']
    description: str
    prompt: str

class ArtifactManagementTool(BaseModel):
    action: typing_extensions.Literal['ArtifactManagement']
    action_type: str
    folder: typing.Optional[str] = None
    pattern: typing.Optional[str] = None
    artifact_type: typing.Optional[str] = None

class BashTool(BaseModel):
    action: typing_extensions.Literal['Bash']
    command: str
    timeout: typing.Optional[int] = None
    description: typing.Optional[str] = None

class DependencyTool(BaseModel):
    action: typing_extensions.Literal['Dependency']
    check_type: typing.Optional[str] = None
    requirements_file: typing.Optional[str] = None
    packages: typing.Optional[typing.List[str]] = None
    update_available: typing.Optional[bool] = None
    include_dev: typing.Optional[bool] = None

class EditOperation(BaseModel):
    old_string: str
    new_string: str
    replace_all: typing.Optional[bool] = None

class EditTool(BaseModel):
    action: typing_extensions.Literal['Edit']
    file_path: str
    old_string: str
    new_string: str
    replace_all: typing.Optional[bool] = None

class ExitPlanModeTool(BaseModel):
    action: typing_extensions.Literal['exit_plan_mode']
    plan: str

class FormatTool(BaseModel):
    action: typing_extensions.Literal['Format']
    target_path: typing.Optional[str] = None
    check_only: typing.Optional[bool] = None
    diff: typing.Optional[bool] = None
    line_length: typing.Optional[int] = None
    skip_string_normalization: typing.Optional[bool] = None
    target_version: typing.Optional[str] = None

class GitAddTool(BaseModel):
    action: typing_extensions.Literal['GitAdd']
    files: typing.Optional[typing.List[str]] = None
    all: typing.Optional[bool] = None
    update: typing.Optional[bool] = None
    patch: typing.Optional[bool] = None
    force: typing.Optional[bool] = None

class GitBranchTool(BaseModel):
    action: typing_extensions.Literal['GitBranch']
    operation: str
    branch_name: typing.Optional[str] = None
    new_name: typing.Optional[str] = None
    remote: typing.Optional[bool] = None
    all: typing.Optional[bool] = None
    merged: typing.Optional[bool] = None
    force: typing.Optional[bool] = None

class GitCommitTool(BaseModel):
    action: typing_extensions.Literal['GitCommit']
    message: str
    amend: typing.Optional[bool] = None
    no_verify: typing.Optional[bool] = None
    signoff: typing.Optional[bool] = None
    author: typing.Optional[str] = None
    allow_empty: typing.Optional[bool] = None

class GitDiffTool(BaseModel):
    action: typing_extensions.Literal['GitDiff']
    target_path: typing.Optional[str] = None
    reference: typing.Optional[str] = None
    staged: typing.Optional[bool] = None
    stat: typing.Optional[bool] = None
    context_lines: typing.Optional[int] = None
    ignore_whitespace: typing.Optional[bool] = None

class GitLogTool(BaseModel):
    action: typing_extensions.Literal['GitLog']
    max_count: typing.Optional[int] = None
    since: typing.Optional[str] = None
    until: typing.Optional[str] = None
    author: typing.Optional[str] = None
    grep: typing.Optional[str] = None
    file_path: typing.Optional[str] = None
    graph: typing.Optional[bool] = None
    oneline: typing.Optional[bool] = None

class GitMergeTool(BaseModel):
    action: typing_extensions.Literal['GitMerge']
    operation: str
    branch_name: typing.Optional[str] = None
    no_ff: typing.Optional[bool] = None
    squash: typing.Optional[bool] = None
    strategy: typing.Optional[str] = None
    message: typing.Optional[str] = None

class GitRebaseTool(BaseModel):
    action: typing_extensions.Literal['GitRebase']
    operation: str
    target_branch: typing.Optional[str] = None
    interactive: typing.Optional[bool] = None
    preserve_merges: typing.Optional[bool] = None
    autostash: typing.Optional[bool] = None

class GitRemoteTool(BaseModel):
    action: typing_extensions.Literal['GitRemote']
    operation: str
    remote_name: typing.Optional[str] = None
    branch_name: typing.Optional[str] = None
    all: typing.Optional[bool] = None
    force: typing.Optional[bool] = None
    prune: typing.Optional[bool] = None
    set_upstream: typing.Optional[bool] = None

class GitResetTool(BaseModel):
    action: typing_extensions.Literal['GitReset']
    operation: str
    target: typing.Optional[str] = None
    file_path: typing.Optional[str] = None
    force: typing.Optional[bool] = None

class GitStashTool(BaseModel):
    action: typing_extensions.Literal['GitStash']
    operation: str
    stash_name: typing.Optional[str] = None
    include_untracked: typing.Optional[bool] = None
    keep_index: typing.Optional[bool] = None
    patch: typing.Optional[bool] = None

class GitStatusTool(BaseModel):
    action: typing_extensions.Literal['GitStatus']
    short_format: typing.Optional[bool] = None
    untracked_files: typing.Optional[str] = None
    ignored: typing.Optional[bool] = None

class GitTagTool(BaseModel):
    action: typing_extensions.Literal['GitTag']
    operation: str
    tag_name: typing.Optional[str] = None
    message: typing.Optional[str] = None
    target: typing.Optional[str] = None
    force: typing.Optional[bool] = None
    pattern: typing.Optional[str] = None

class GlobTool(BaseModel):
    action: typing_extensions.Literal['Glob']
    pattern: str
    path: typing.Optional[str] = None

class GrepTool(BaseModel):
    action: typing_extensions.Literal['Grep']
    pattern: str
    path: typing.Optional[str] = None
    include: typing.Optional[str] = None

class InstallPackagesTool(BaseModel):
    action: typing_extensions.Literal['InstallPackages']
    packages: typing.List[str]
    dev: typing.Optional[bool] = None
    upgrade: typing.Optional[bool] = None
    user_confirmed: bool

class LSTool(BaseModel):
    action: typing_extensions.Literal['LS']
    path: str
    ignore: typing.Optional[typing.List[str]] = None

class LintTool(BaseModel):
    action: typing_extensions.Literal['Lint']
    target_path: typing.Optional[str] = None
    fix: typing.Optional[bool] = None
    show_fixes: typing.Optional[bool] = None
    select_codes: typing.Optional[str] = None
    ignore: typing.Optional[str] = None
    format: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    message: typing.Union[str, "BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "InstallPackagesTool", "ArtifactManagementTool", "GitStatusTool", "GitLogTool", "GitAddTool", "GitCommitTool", "GitBranchTool", "GitDiffTool", "GitRemoteTool", "GitStashTool", "GitMergeTool", "GitRebaseTool", "GitTagTool", "GitResetTool", "AgentTool"]

class MultiEditTool(BaseModel):
    action: typing_extensions.Literal['MultiEdit']
    file_path: str
    edits: typing.List["EditOperation"]

class NotebookEditTool(BaseModel):
    action: typing_extensions.Literal['NotebookEdit']
    notebook_path: str
    cell_number: int
    new_source: str
    cell_type: typing.Optional[str] = None
    edit_mode: typing.Optional[str] = None

class NotebookReadTool(BaseModel):
    action: typing_extensions.Literal['NotebookRead']
    notebook_path: str

class PytestRunTool(BaseModel):
    action: typing_extensions.Literal['PytestRun']
    test_path: typing.Optional[str] = None
    verbose: typing.Optional[bool] = None
    capture: typing.Optional[str] = None
    markers: typing.Optional[str] = None
    keywords: typing.Optional[str] = None
    max_failures: typing.Optional[int] = None
    timeout: typing.Optional[int] = None

class ReadTool(BaseModel):
    action: typing_extensions.Literal['Read']
    file_path: str
    offset: typing.Optional[int] = None
    limit: typing.Optional[int] = None

class ReplyToUser(BaseModel):
    action: typing_extensions.Literal['reply_to_user']
    message: str

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class TodoItem(BaseModel):
    content: str
    status: typing.Union[typing_extensions.Literal['pending'], typing_extensions.Literal['in_progress'], typing_extensions.Literal['completed']]
    priority: typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]
    id: str

class TodoReadTool(BaseModel):
    action: typing_extensions.Literal['TodoRead']

class TodoWriteTool(BaseModel):
    action: typing_extensions.Literal['TodoWrite']
    todos: typing.List["TodoItem"]

class TypeCheckTool(BaseModel):
    action: typing_extensions.Literal['TypeCheck']
    target_path: typing.Optional[str] = None
    checker: typing.Optional[str] = None
    strict: typing.Optional[bool] = None
    ignore_missing_imports: typing.Optional[bool] = None
    incremental: typing.Optional[bool] = None
    config_file: typing.Optional[str] = None

class WebFetchTool(BaseModel):
    action: typing_extensions.Literal['WebFetch']
    url: str
    prompt: str
    save_to_file: typing.Optional[str] = None

class WebSearchTool(BaseModel):
    action: typing_extensions.Literal['WebSearch']
    query: str
    allowed_domains: typing.Optional[typing.List[str]] = None
    blocked_domains: typing.Optional[typing.List[str]] = None

class WriteTool(BaseModel):
    action: typing_extensions.Literal['Write']
    file_path: str
    content: str

# #########################################################################
# Generated type aliases (5)
# #########################################################################


AgentTools: typing_extensions.TypeAlias = typing.Union["BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "InstallPackagesTool", "ArtifactManagementTool", "GitStatusTool", "GitLogTool", "GitAddTool", "GitCommitTool", "GitBranchTool", "GitDiffTool", "GitRemoteTool", "GitStashTool", "GitMergeTool", "GitRebaseTool", "GitTagTool", "GitResetTool", "AgentTool"]


CodingTools: typing_extensions.TypeAlias = typing.Union["PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "InstallPackagesTool", "ArtifactManagementTool", "GitStatusTool", "GitLogTool", "GitAddTool", "GitCommitTool", "GitBranchTool", "GitDiffTool", "GitRemoteTool", "GitStashTool", "GitMergeTool", "GitRebaseTool", "GitTagTool", "GitResetTool"]


GitTools: typing_extensions.TypeAlias = typing.Union["GitStatusTool", "GitLogTool", "GitAddTool", "GitCommitTool", "GitBranchTool", "GitDiffTool", "GitRemoteTool", "GitStashTool", "GitMergeTool", "GitRebaseTool", "GitTagTool", "GitResetTool"]


ScaryTools: typing_extensions.TypeAlias = typing.Union["EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "TodoWriteTool"]


SubAgentTools: typing_extensions.TypeAlias = typing.Union["BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "InstallPackagesTool", "ArtifactManagementTool", "GitStatusTool", "GitLogTool", "GitAddTool", "GitCommitTool", "GitBranchTool", "GitDiffTool", "GitRemoteTool", "GitStashTool", "GitMergeTool", "GitRebaseTool", "GitTagTool", "GitResetTool"]
